-- Sprint 25 MX137 — registra ~64 apps open source / weblinks no
-- kernel.app_registry. Modos (iframe vs weblink) determinados pelo
-- script tools/validate-iframe.mjs (MX136), salvos em
-- tools/validate-iframe-results.json.
--
-- Idempotente via ON CONFLICT (id) DO NOTHING — pode rodar varias vezes
-- sem duplicar com os 52 nativos ja seedados em
-- 20260504000006_seed_app_registry.sql.

-- ─── Estende o CHECK de category para abranger novas categorias ─────────────
-- Categorias originais: vertical, optional, ai, productivity, games,
-- utilities, puter, system. Novas: dev-tools, design, data.

ALTER TABLE kernel.app_registry
  DROP CONSTRAINT IF EXISTS app_registry_category_check;

ALTER TABLE kernel.app_registry
  ADD CONSTRAINT app_registry_category_check CHECK (
    category IN (
      'vertical','optional','ai','productivity','games','utilities','puter','system',
      'dev-tools','design','data'
    )
  );

-- ─── INSERT em massa ────────────────────────────────────────────────────────
-- Convencao: app externo => show_in_dock=false, sort_order >= 200,
-- has_internal_nav=false, always_enabled=false, installable=true, closeable=true.
-- entry_url = external_url para apps weblink/iframe.

INSERT INTO kernel.app_registry
  (id, slug, name, description, long_description, icon, color, category,
   app_type, entry_mode, entry_url, external_url, version, status,
   pricing_model, license, developer_name,
   show_in_dock, closeable, has_internal_nav, always_enabled, opens_as_modal,
   installable, offline_capable, tags, sort_order)
VALUES

-- ─── PRODUTIVIDADE ──────────────────────────────────────────────────────────

('excalidraw','excalidraw','Excalidraw',
 'Whiteboard colaborativo com estilo desenhado a mao.',
 'Excalidraw eh um whiteboard virtual open source para desenho de diagramas, fluxogramas e ideias com estetica feita-a-mao. Suporta sessoes ao vivo e exportacao.',
 'Pencil','#6c5ce7','productivity','open_source','iframe',
 'https://excalidraw.com','https://excalidraw.com','1.0.0','published',
 'free','MIT','Excalidraw',
 false,true,false,false,false,true,false,
 ARRAY['whiteboard','diagrams','collab','open-source'],200),

('draw-io','draw-io','draw.io',
 'Editor de diagramas online (UML, BPMN, fluxos).',
 'draw.io / diagrams.net eh editor visual de diagramas profissional, com bibliotecas extensas (UML, BPMN, AWS, Azure). Salva localmente ou em Drive/GDrive.',
 'GitBranch','#f09819','productivity','open_source','weblink',
 'https://app.diagrams.net','https://app.diagrams.net','1.0.0','published',
 'free','Apache-2.0','JGraph',
 false,true,false,false,false,true,false,
 ARRAY['diagrams','uml','bpmn','open-source'],201),

('tldraw','tldraw','Tldraw',
 'Canvas infinito para desenho colaborativo.',
 'Tldraw eh um canvas infinito moderno para sketches, wireframes e diagramas, com formas inteligentes e collab opcional.',
 'PenTool','#1e90ff','productivity','open_source','iframe',
 'https://www.tldraw.com','https://www.tldraw.com','1.0.0','published',
 'free','Apache-2.0','tldraw',
 false,true,false,false,false,true,false,
 ARRAY['canvas','sketch','collab','open-source'],202),

('affine','affine','AFFiNE',
 'Workspace tipo Notion + Miro open source.',
 'AFFiNE combina docs, whiteboard e bases de dados em um workspace local-first. Alternativa open source ao Notion + Miro.',
 'Layout','#5b57d1','productivity','open_source','weblink',
 'https://app.affine.pro','https://app.affine.pro','1.0.0','published',
 'free','MIT','Toeverything',
 false,true,false,false,false,true,false,
 ARRAY['workspace','docs','notes','local-first'],203),

('stackedit','stackedit','StackEdit',
 'Editor Markdown com preview lado a lado.',
 'StackEdit eh editor Markdown PWA com sync para Drive/Dropbox/GitHub e LaTeX/Mermaid embutidos.',
 'FileText','#0288d1','productivity','open_source','iframe',
 'https://stackedit.io/app','https://stackedit.io/app','1.0.0','published',
 'free','Apache-2.0','StackEdit',
 false,true,false,false,false,true,false,
 ARRAY['markdown','editor','docs','open-source'],204),

('mermaid-live','mermaid-live','Mermaid Live',
 'Editor de diagramas Mermaid (diagrams as code).',
 'Mermaid Live Editor renderiza diagramas escritos em sintaxe Mermaid (sequencia, flow, gantt, classes) instantaneamente.',
 'GitBranch','#ff6f61','dev-tools','open_source','iframe',
 'https://mermaid.live','https://mermaid.live','1.0.0','published',
 'free','MIT','Mermaid',
 false,true,false,false,false,true,false,
 ARRAY['mermaid','diagrams-as-code','dev-tools'],205),

('markmap','markmap','Markmap',
 'Mapas mentais a partir de Markdown.',
 'Markmap converte listas Markdown hierarquicas em mapas mentais interativos. Util para brainstorming e organizacao de ideias.',
 'Network','#10ac84','productivity','open_source','iframe',
 'https://markmap.js.org/repl','https://markmap.js.org/repl','1.0.0','published',
 'free','MIT','Markmap',
 false,true,false,false,false,true,false,
 ARRAY['mindmap','markdown','open-source'],206),

('cal-com','cal-com','Cal.com',
 'Agendamento de reunioes (open source Calendly).',
 'Cal.com eh alternativa open source ao Calendly: calendarios compartilhaveis, integracoes (Google/Outlook/Zoom) e team scheduling.',
 'Calendar','#292929','productivity','open_source','iframe',
 'https://cal.com','https://cal.com','1.0.0','published',
 'free','AGPL-3.0','Cal.com Inc.',
 false,true,false,false,false,true,false,
 ARRAY['scheduling','calendar','open-source'],207),

('rallly','rallly','Rallly',
 'Enquetes de agendamento (Doodle alternativo).',
 'Rallly cria links de votacao para escolher data/horario de reunioes em grupo. Alternativa open source ao Doodle.',
 'CalendarCheck','#4f46e5','productivity','open_source','iframe',
 'https://rallly.co','https://rallly.co','1.0.0','published',
 'free','AGPL-3.0','Rallly',
 false,true,false,false,false,true,false,
 ARRAY['scheduling','polls','open-source'],208),

-- ─── DEV-TOOLS (extras da validacao + listados) ─────────────────────────────

('hoppscotch','hoppscotch','Hoppscotch',
 'Cliente de API REST/GraphQL no browser.',
 'Hoppscotch eh alternativa open source ao Postman: REST, GraphQL, WebSocket, SSE e MQTT direto no navegador, sem instalar nada.',
 'Send','#33bb78','dev-tools','open_source','weblink',
 'https://hoppscotch.io','https://hoppscotch.io','1.0.0','published',
 'free','MIT','Hoppscotch',
 false,true,false,false,false,true,false,
 ARRAY['api','rest','graphql','dev-tools'],220),

('swagger-editor','swagger-editor','Swagger Editor',
 'Editor visual para OpenAPI/Swagger specs.',
 'Swagger Editor permite escrever, validar e visualizar especificacoes OpenAPI 3.x diretamente no navegador.',
 'FileCode','#85ea2d','dev-tools','open_source','iframe',
 'https://editor.swagger.io','https://editor.swagger.io','1.0.0','published',
 'free','Apache-2.0','SmartBear',
 false,true,false,false,false,true,false,
 ARRAY['openapi','swagger','api-docs','dev-tools'],221),

('jsoncrack','jsoncrack','JSON Crack',
 'Visualizador interativo de JSON/YAML.',
 'JSON Crack transforma JSON, YAML, XML e CSV em diagramas de no interativos, facilitando a inspecao de estruturas grandes.',
 'Network','#ffba1a','dev-tools','open_source','iframe',
 'https://jsoncrack.com/editor','https://jsoncrack.com/editor','1.0.0','published',
 'free','MIT','JSON Crack',
 false,true,false,false,false,true,false,
 ARRAY['json','visualizer','dev-tools'],222),

('jsonhero','jsonhero','JSON Hero',
 'Inspetor amigavel de JSON.',
 'JSON Hero exibe JSON com vistas mais legiveis (arvore, colunas, tabela) e detecta automaticamente datas, URLs e imagens.',
 'FileJson','#7c3aed','dev-tools','open_source','iframe',
 'https://jsonhero.io','https://jsonhero.io','1.0.0','published',
 'free','MIT','Trigger.dev',
 false,true,false,false,false,true,false,
 ARRAY['json','viewer','dev-tools'],223),

('cyberchef','cyberchef','CyberChef',
 'Canivete suico de transformacao de dados (GCHQ).',
 'CyberChef encadeia operacoes de codificacao, criptografia, parsing e analise de dados em uma "receita" visual. Mantido pelo GCHQ.',
 'ChefHat','#1e88e5','dev-tools','open_source','iframe',
 'https://gchq.github.io/CyberChef','https://gchq.github.io/CyberChef','1.0.0','published',
 'free','Apache-2.0','GCHQ',
 false,true,false,false,false,true,false,
 ARRAY['encoding','crypto','data','security','dev-tools'],224),

('it-tools','it-tools','IT Tools',
 'Coletanea de utilitarios para devs.',
 'IT Tools agrega dezenas de pequenas ferramentas (UUID, hash, regex, JWT, base64, color converter etc) em uma so PWA.',
 'Wrench','#18a058','dev-tools','open_source','iframe',
 'https://it-tools.tech','https://it-tools.tech','1.0.0','published',
 'free','GPL-3.0','CorentinTh',
 false,true,false,false,false,true,false,
 ARRAY['utilities','dev-tools','swiss-army'],225),

('sqlime','sqlime','Sqlime',
 'Playground SQLite no browser.',
 'Sqlime eh playground SQLite serverless: cria bancos in-memory, executa queries e compartilha snippets via URL.',
 'Database','#0ea5e9','dev-tools','open_source','iframe',
 'https://sqlime.org','https://sqlime.org','1.0.0','published',
 'free','MIT','nalgeon',
 false,true,false,false,false,true,false,
 ARRAY['sql','sqlite','playground','dev-tools'],226),

('webhook-site','webhook-site','Webhook.site',
 'Recebe e inspeciona webhooks em tempo real.',
 'Webhook.site gera URLs descartaveis para inspecionar payloads HTTP enviados por servicos de terceiros — util para debug de webhooks.',
 'Webhook','#1f78d1','dev-tools','open_source','weblink',
 'https://webhook.site','https://webhook.site','1.0.0','published',
 'free','MIT','Webhook.site',
 false,true,false,false,false,true,false,
 ARRAY['webhook','http','debug','dev-tools'],227),

('regex101','regex101','regex101',
 'Tester e debugger de expressoes regulares.',
 'regex101 testa, explica e otimiza expressoes regulares em PCRE, JavaScript, Python e Go com destaque em tempo real.',
 'Regex','#5c6bc0','dev-tools','open_source','weblink',
 'https://regex101.com','https://regex101.com','1.0.0','published',
 'free','proprietary','firasdib',
 false,true,false,false,false,true,false,
 ARRAY['regex','dev-tools'],228),

('vscode-dev','vscode-dev','VS Code (web)',
 'Editor VS Code rodando no navegador.',
 'VS Code para web abre repositorios GitHub e disco local diretamente no navegador, com syntax highlight e extensoes.',
 'Code','#007acc','dev-tools','embedded_external','weblink',
 'https://vscode.dev','https://vscode.dev','1.0.0','published',
 'free','proprietary','Microsoft',
 false,true,false,false,false,true,false,
 ARRAY['ide','editor','dev-tools'],229),

-- ─── DESIGN & MIDIA ─────────────────────────────────────────────────────────

('photopea','photopea','Photopea',
 'Photoshop no browser (PSD/AI compativel).',
 'Photopea abre arquivos PSD, AI, Sketch, XD e GIMP no navegador. Ferramentas equivalentes ao Photoshop, gratuito.',
 'Image','#18a497','design','embedded_external','iframe',
 'https://www.photopea.com','https://www.photopea.com','1.0.0','published',
 'free','proprietary','Photopea',
 false,true,false,false,false,true,false,
 ARRAY['image','editor','psd','design'],240),

('squoosh','squoosh','Squoosh',
 'Compressor de imagens do Google.',
 'Squoosh eh PWA do Google para comprimir e converter imagens (JPEG, WebP, AVIF) com preview lado a lado.',
 'ImageDown','#ff6347','design','open_source','iframe',
 'https://squoosh.app','https://squoosh.app','1.0.0','published',
 'free','Apache-2.0','Google Chrome Labs',
 false,true,false,false,false,true,false,
 ARRAY['image','compression','design'],241),

('svgomg','svgomg','SVGOMG',
 'Otimizador SVG online.',
 'SVGOMG eh frontend visual para SVGO: comprime SVGs removendo metadados redundantes e mostra diff em tempo real.',
 'FileImage','#ffb13b','design','open_source','iframe',
 'https://jakearchibald.github.io/svgomg/','https://jakearchibald.github.io/svgomg/','1.0.0','published',
 'free','MIT','Jake Archibald',
 false,true,false,false,false,true,false,
 ARRAY['svg','optimizer','design'],242),

('minipaint','minipaint','MiniPaint',
 'Editor de imagens leve no browser.',
 'MiniPaint eh editor de imagens com camadas, filtros e ferramentas basicas — alternativa leve ao Photoshop, 100% browser.',
 'Paintbrush','#2196f3','design','open_source','iframe',
 'https://viliusle.github.io/miniPaint/','https://viliusle.github.io/miniPaint/','1.0.0','published',
 'free','MIT','viliusle',
 false,true,false,false,false,true,false,
 ARRAY['image','editor','design'],243),

('polotno','polotno','Polotno Studio',
 'Editor de designs canvas (Canva-like).',
 'Polotno Studio eh editor de designs visuais para posts, banners e cards baseado na biblioteca Polotno.',
 'Palette','#8b5cf6','design','open_source','iframe',
 'https://studio.polotno.com','https://studio.polotno.com','1.0.0','published',
 'free','MIT','Polotno',
 false,true,false,false,false,true,false,
 ARRAY['design','canvas','social'],244),

('audiomass','audiomass','AudioMass',
 'Editor de audio puro no browser.',
 'AudioMass edita arquivos de audio (corte, fade, EQ, efeitos) inteiramente no navegador — equivalente leve ao Audacity.',
 'Music','#e91e63','design','open_source','iframe',
 'https://audiomass.co','https://audiomass.co','1.0.0','published',
 'free','MIT','pkalogiros',
 false,true,false,false,false,true,false,
 ARRAY['audio','editor','design'],245),

('slidev','slidev','Slidev',
 'Apresentacoes para devs (Markdown).',
 'Slidev gera apresentacoes a partir de Markdown com syntax-highlighting, animacoes e exportacao para PDF/PNG.',
 'Presentation','#2b90b6','dev-tools','open_source','iframe',
 'https://sli.dev','https://sli.dev','1.0.0','published',
 'free','MIT','Slidev',
 false,true,false,false,false,true,false,
 ARRAY['slides','markdown','presentation','dev-tools'],246),

('canva','canva','Canva',
 'Plataforma de design visual.',
 'Canva oferece templates prontos para posts, slides, videos e impressos. Versao gratuita generosa, premium opcional.',
 'Palette','#00c4cc','design','embedded_external','weblink',
 'https://www.canva.com','https://www.canva.com','1.0.0','published',
 'free','proprietary','Canva',
 false,true,false,false,false,true,false,
 ARRAY['design','templates'],247),

('figma','figma','Figma',
 'Design e prototipagem em equipe.',
 'Figma eh ferramenta colaborativa de UI/UX e prototipagem. Versao gratuita para times pequenos.',
 'Figma','#f24e1e','design','embedded_external','weblink',
 'https://www.figma.com','https://www.figma.com','1.0.0','published',
 'free','proprietary','Figma Inc.',
 false,true,false,false,false,true,false,
 ARRAY['design','ux','prototyping'],248),

-- ─── IA ─────────────────────────────────────────────────────────────────────

('claude','claude','Claude',
 'Assistente IA da Anthropic.',
 'Claude eh assistente de IA conversacional da Anthropic, com janela de contexto longa e ferramentas (artifacts, computer use).',
 'Bot','#d4a574','ai','embedded_external','weblink',
 'https://claude.ai','https://claude.ai','1.0.0','published',
 'free','proprietary','Anthropic',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','chat'],260),

('chatgpt','chatgpt','ChatGPT',
 'Assistente IA da OpenAI.',
 'ChatGPT eh produto da OpenAI baseado em modelos GPT. Plano gratuito limitado, plano Plus desbloqueia GPT-4 e ferramentas.',
 'Bot','#10a37f','ai','embedded_external','weblink',
 'https://chat.openai.com','https://chat.openai.com','1.0.0','published',
 'free','proprietary','OpenAI',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','chat'],261),

('gemini','gemini','Gemini',
 'Assistente IA do Google.',
 'Gemini eh assistente IA multimodal da Google, integrado a Workspace e Search.',
 'Sparkles','#4285f4','ai','embedded_external','weblink',
 'https://gemini.google.com','https://gemini.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','google'],262),

('perplexity','perplexity','Perplexity',
 'Search com respostas geradas por IA.',
 'Perplexity combina busca web com LLMs, retornando respostas com citacoes verificaveis.',
 'Search','#20808d','ai','embedded_external','weblink',
 'https://www.perplexity.ai','https://www.perplexity.ai','1.0.0','published',
 'free','proprietary','Perplexity AI',
 false,true,false,false,false,true,false,
 ARRAY['ai','search','citations'],263),

('huggingchat','huggingchat','HuggingChat',
 'Chat com modelos open source (Hugging Face).',
 'HuggingChat conversa com LLMs open source hospedados na Hugging Face (Llama, Mixtral, Qwen) — sem login obrigatorio.',
 'Bot','#ff9d00','ai','open_source','weblink',
 'https://huggingface.co/chat','https://huggingface.co/chat','1.0.0','published',
 'free','Apache-2.0','Hugging Face',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','open-source'],264),

('puter-ai','puter-ai','Puter AI',
 'IA gratuita via Puter.com.',
 'Puter eh OS no browser open source com IA gratuita embutida (GPT-4o, Claude, Gemini sem API key).',
 'Cpu','#3b82f6','ai','open_source','weblink',
 'https://puter.com','https://puter.com','1.0.0','published',
 'free','AGPL-3.0','Puter',
 false,true,false,false,false,true,false,
 ARRAY['ai','os','open-source'],265),

('poe','poe','Poe',
 'Agregador de bots IA (Quora).',
 'Poe agrega varios bots IA (Claude, ChatGPT, Llama, etc) em uma unica interface, com criacao de bots customizados.',
 'MessageCircle','#6c63ff','ai','embedded_external','weblink',
 'https://poe.com','https://poe.com','1.0.0','published',
 'free','proprietary','Quora',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','aggregator'],266),

('copilot','copilot','Microsoft Copilot',
 'IA da Microsoft.',
 'Microsoft Copilot eh assistente IA integrado a Bing/Edge/Office, alimentado por modelos GPT e Microsoft.',
 'Bot','#0078d4','ai','embedded_external','iframe',
 'https://copilot.microsoft.com','https://copilot.microsoft.com','1.0.0','published',
 'free','proprietary','Microsoft',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','microsoft'],267),

('grok','grok','Grok',
 'IA do X/Twitter.',
 'Grok eh assistente IA da xAI integrado ao X (Twitter), com personalidade direta e acesso a feeds em tempo real.',
 'Zap','#1da1f2','ai','embedded_external','weblink',
 'https://grok.x.ai','https://grok.x.ai','1.0.0','published',
 'free','proprietary','xAI',
 false,true,false,false,false,true,false,
 ARRAY['ai','llm','x'],268),

-- ─── UTILIDADES ─────────────────────────────────────────────────────────────

('sharedrop','sharedrop','ShareDrop',
 'Transferencia de arquivos P2P (AirDrop web).',
 'ShareDrop eh AirDrop web baseado em WebRTC: transfere arquivos diretamente entre dispositivos na mesma rede.',
 'Share2','#3498db','utilities','open_source','iframe',
 'https://www.sharedrop.io','https://www.sharedrop.io','1.0.0','published',
 'free','MIT','cowbell-labs',
 false,true,false,false,false,true,false,
 ARRAY['p2p','file-transfer','utilities'],280),

('snapdrop','snapdrop','Snapdrop',
 'Transferencia de arquivos local (LAN).',
 'Snapdrop tambem eh AirDrop web (alternativa ao ShareDrop), focado em descoberta automatica na LAN.',
 'Share2','#1abc9c','utilities','open_source','iframe',
 'https://snapdrop.net','https://snapdrop.net','1.0.0','published',
 'free','MIT','RobinLinus',
 false,true,false,false,false,true,false,
 ARRAY['p2p','file-transfer','lan','utilities'],281),

('monkeytype','monkeytype','MonkeyType',
 'Teste de velocidade de digitacao.',
 'MonkeyType mede WPM, accuracy e consistencia em testes de digitacao customizaveis. Open source, sem ads.',
 'Keyboard','#e2b714','utilities','open_source','weblink',
 'https://monkeytype.com','https://monkeytype.com','1.0.0','published',
 'free','GPL-3.0','Monkeytype',
 false,true,false,false,false,true,false,
 ARRAY['typing','wpm','utilities'],282),

('pomofocus','pomofocus','Pomofocus',
 'Timer Pomodoro online.',
 'Pomofocus aplica a tecnica Pomodoro (25/5min) com fila de tarefas, sons e estatisticas diarias.',
 'Timer','#d95550','utilities','embedded_external','weblink',
 'https://pomofocus.io','https://pomofocus.io','1.0.0','published',
 'free','proprietary','Pomofocus',
 false,true,false,false,false,true,false,
 ARRAY['pomodoro','productivity','utilities'],283),

('lorem-ipsum','lorem-ipsum','Lorem Ipsum',
 'Gerador de texto placeholder.',
 'Lorem Ipsum gera paragrafos, palavras ou listas em latim falso para uso em mockups e designs.',
 'Type','#64748b','utilities','embedded_external','iframe',
 'https://loremipsum.io','https://loremipsum.io','1.0.0','published',
 'free','proprietary','Lorem Ipsum',
 false,true,false,false,false,true,false,
 ARRAY['placeholder','utilities','design'],284),

('speedtest','speedtest','SpeedTest (fast.com)',
 'Teste de velocidade de internet (Netflix).',
 'fast.com mede velocidade de download/upload e latencia, hospedado pela Netflix.',
 'Wifi','#e50914','utilities','embedded_external','iframe',
 'https://fast.com','https://fast.com','1.0.0','published',
 'free','proprietary','Netflix',
 false,true,false,false,false,true,false,
 ARRAY['network','speedtest','utilities'],285),

('qrcode-gen','qrcode-gen','QR Code Generator',
 'Gerador de QR Codes customizaveis.',
 'QRCode Monkey gera QR codes coloridos, com logo e em alta resolucao para impressao.',
 'QrCode','#000000','utilities','embedded_external','iframe',
 'https://www.qrcode-monkey.com','https://www.qrcode-monkey.com','1.0.0','published',
 'free','proprietary','QRCode Monkey',
 false,true,false,false,false,true,false,
 ARRAY['qrcode','utilities'],286),

('color-hunt','color-hunt','Color Hunt',
 'Catalogo de paletas de cores.',
 'Color Hunt eh galeria curada de paletas de cores submetidas pela comunidade — util para inspirar designs.',
 'Palette','#ff6b6b','design','embedded_external','iframe',
 'https://colorhunt.co','https://colorhunt.co','1.0.0','published',
 'free','proprietary','Color Hunt',
 false,true,false,false,false,true,false,
 ARRAY['palettes','color','design'],287),

('emojipedia','emojipedia','Emojipedia',
 'Enciclopedia de emojis.',
 'Emojipedia documenta significado, historia e renderizacao de emojis em todas as plataformas.',
 'Smile','#ffcc33','utilities','embedded_external','weblink',
 'https://emojipedia.org','https://emojipedia.org','1.0.0','published',
 'free','proprietary','Emojipedia',
 false,true,false,false,false,true,false,
 ARRAY['emoji','reference','utilities'],288),

('removebg','removebg','Remove.bg',
 'Remover fundo de imagens com IA.',
 'Remove.bg detecta sujeito e remove fundo automaticamente, retornando PNG com transparencia.',
 'Eraser','#1460ff','design','embedded_external','weblink',
 'https://www.remove.bg','https://www.remove.bg','1.0.0','published',
 'free','proprietary','Kaleido AI',
 false,true,false,false,false,true,false,
 ARRAY['image','background','design'],289),

('tinypng','tinypng','TinyPNG',
 'Compressor de PNG/JPEG.',
 'TinyPNG comprime PNG/JPEG/WebP via algoritmo lossy inteligente, mantendo qualidade visual.',
 'FileImage','#a5ce3a','utilities','embedded_external','weblink',
 'https://tinypng.com','https://tinypng.com','1.0.0','published',
 'free','proprietary','Voormedia',
 false,true,false,false,false,true,false,
 ARRAY['image','compression','utilities'],290),

('temp-mail','temp-mail','Temp Mail',
 'Email temporario descartavel.',
 'Temp Mail gera enderecos de email descartaveis para receber confirmacoes sem expor seu email real.',
 'Mail','#1a73e8','utilities','embedded_external','weblink',
 'https://temp-mail.org','https://temp-mail.org','1.0.0','published',
 'free','proprietary','Temp Mail',
 false,true,false,false,false,true,false,
 ARRAY['email','temporary','privacy','utilities'],291),

-- ─── JOGOS ──────────────────────────────────────────────────────────────────

('game-2048','game-2048','2048',
 'Puzzle numerico classico (2048).',
 'Combine numeros iguais para formar 2048. Jogo aditivo do Gabriele Cirulli, open source.',
 'Grid3x3','#edc22e','games','open_source','weblink',
 'https://play2048.co','https://play2048.co','1.0.0','published',
 'free','MIT','Gabriele Cirulli',
 false,true,false,false,false,true,false,
 ARRAY['puzzle','games'],300),

('game-hexgl','game-hexgl','HexGL',
 'Corrida futurista 3D em WebGL.',
 'HexGL eh jogo de corrida futurista (estilo F-Zero/Wipeout) renderizado em WebGL, totalmente browser.',
 'Rocket','#00ff88','games','open_source','iframe',
 'https://hexgl.bkcore.com','https://hexgl.bkcore.com','1.0.0','published',
 'free','MIT','BKcore',
 false,true,false,false,false,true,false,
 ARRAY['racing','3d','webgl','games'],301),

('game-hextris','game-hextris','Hextris',
 'Tetris hexagonal.',
 'Hextris reinventa Tetris com pecas que caem em hexagono central — minimalista e viciante.',
 'Hexagon','#e91e63','games','open_source','iframe',
 'https://hextris.io','https://hextris.io','1.0.0','published',
 'free','GPL-3.0','Hextris',
 false,true,false,false,false,true,false,
 ARRAY['puzzle','games'],302),

('game-lichess','game-lichess','Lichess',
 'Xadrez online open source.',
 'Lichess eh plataforma de xadrez 100% gratuita e sem ads, com analise, puzzles, torneios e variantes.',
 'Crown','#ffffff','games','open_source','weblink',
 'https://lichess.org','https://lichess.org','1.0.0','published',
 'free','AGPL-3.0','Lichess',
 false,true,false,false,false,true,false,
 ARRAY['chess','multiplayer','open-source','games'],303),

('game-openscope','game-openscope','OpenScope ATC',
 'Simulador de controle de trafego aereo.',
 'OpenScope simula controle de trafego aereo em aeroportos reais, com radar e instrucoes de aproximacao.',
 'Plane','#1e90ff','games','open_source','weblink',
 'https://openscope.co','https://openscope.co','1.0.0','published',
 'free','MIT','OpenScope',
 false,true,false,false,false,true,false,
 ARRAY['simulation','atc','games'],304),

('game-pacman','game-pacman','Pacman HTML5',
 'Pac-Man classico em HTML5.',
 'Pacman HTML5 reimplementa o classico de arcade no navegador, com controles teclado.',
 'Ghost','#ffeb3b','games','open_source','iframe',
 'https://passer-by.com/pacman/','https://passer-by.com/pacman/','1.0.0','published',
 'free','MIT','passer-by',
 false,true,false,false,false,true,false,
 ARRAY['arcade','classic','games'],305),

('game-chess','game-chess','Chess.com',
 'Xadrez online (Chess.com).',
 'Chess.com eh maior plataforma de xadrez do mundo, com puzzles, aulas e bots de varios niveis.',
 'Crown','#769656','games','embedded_external','weblink',
 'https://www.chess.com','https://www.chess.com','1.0.0','published',
 'free','proprietary','Chess.com',
 false,true,false,false,false,true,false,
 ARRAY['chess','multiplayer','games'],306),

('game-wordle','game-wordle','Wordle',
 'Jogo diario de adivinhar palavras (NYT).',
 'Wordle eh puzzle diario do New York Times: adivinhe a palavra de 5 letras em 6 tentativas.',
 'LetterText','#6aaa64','games','embedded_external','weblink',
 'https://www.nytimes.com/games/wordle','https://www.nytimes.com/games/wordle','1.0.0','published',
 'free','proprietary','New York Times',
 false,true,false,false,false,true,false,
 ARRAY['puzzle','daily','games'],307),

('game-sudoku','game-sudoku','Sudoku Web',
 'Sudoku classico online.',
 'Sudoku.com oferece grades diarias em multiplas dificuldades, com dicas e estatisticas.',
 'Grid3x3','#344861','games','embedded_external','weblink',
 'https://sudoku.com','https://sudoku.com','1.0.0','published',
 'free','proprietary','Easybrain',
 false,true,false,false,false,true,false,
 ARRAY['sudoku','puzzle','games'],308),

('game-crossword','game-crossword','Crossword (NYT)',
 'Palavras cruzadas do New York Times.',
 'Crosswords do NYT inclui mini, daily e variantes — referencia em palavras cruzadas em ingles.',
 'LetterText','#121212','games','embedded_external','weblink',
 'https://www.nytimes.com/crosswords','https://www.nytimes.com/crosswords','1.0.0','published',
 'free','proprietary','New York Times',
 false,true,false,false,false,true,false,
 ARRAY['crossword','puzzle','games'],309),

('game-minesweeper','game-minesweeper','Minesweeper',
 'Campo minado online.',
 'Minesweeper.online eh implementacao multiplayer com leaderboards globais e modos especiais.',
 'Bomb','#c0c0c0','games','embedded_external','iframe',
 'https://minesweeper.online','https://minesweeper.online','1.0.0','published',
 'free','proprietary','Minesweeper.online',
 false,true,false,false,false,true,false,
 ARRAY['minesweeper','puzzle','games'],310),

('game-solitaire','game-solitaire','Solitaire',
 'Paciencia classica.',
 'Solitaire.io oferece variantes de paciencia (Klondike, Spider, FreeCell) jogaveis no navegador.',
 'Club','#006600','games','embedded_external','iframe',
 'https://solitaire.io','https://solitaire.io','1.0.0','published',
 'free','proprietary','Solitaire.io',
 false,true,false,false,false,true,false,
 ARRAY['cards','solitaire','games'],311),

('game-snake-io','game-snake-io','Slither.io',
 'Snake multiplayer.',
 'Slither.io eh evolucao multiplayer do snake classico — cresca devorando pellets, evite outras cobras.',
 'Bug','#4ade80','games','embedded_external','iframe',
 'https://slither.io','https://slither.io','1.0.0','published',
 'free','proprietary','Steve Howse',
 false,true,false,false,false,true,false,
 ARRAY['snake','multiplayer','io','games'],312),

('game-agar','game-agar','Agar.io',
 'Celulas multiplayer (agar).',
 'Agar.io eh classico .io multiplayer: celulas crescem absorvendo pellets e celulas menores.',
 'Circle','#22d3ee','games','embedded_external','iframe',
 'https://agar.io','https://agar.io','1.0.0','published',
 'free','proprietary','Miniclip',
 false,true,false,false,false,true,false,
 ARRAY['multiplayer','io','games'],313),

('game-geoguessr','game-geoguessr','GeoGuessr',
 'Quiz geografico (Street View).',
 'GeoGuessr coloca voce em local aleatorio do Street View — adivinhe onde esta no mapa-mundi.',
 'MapPin','#2ea840','games','embedded_external','iframe',
 'https://www.geoguessr.com','https://www.geoguessr.com','1.0.0','published',
 'free','proprietary','GeoGuessr',
 false,true,false,false,false,true,false,
 ARRAY['geography','quiz','games'],314),

-- ─── DEV-TOOLS (extras para hit 80+) ────────────────────────────────────────

('jwt-io','jwt-io','JWT.io',
 'Decoder e verificador de JWT.',
 'JWT.io decodifica e valida tokens JWT, mostrando header, payload e signature. Suporta HS256/RS256 e exibe libs por linguagem.',
 'Key','#d63aff','dev-tools','embedded_external','weblink',
 'https://jwt.io','https://jwt.io','1.0.0','published',
 'free','proprietary','Auth0',
 false,true,false,false,false,true,false,
 ARRAY['jwt','auth','debug','dev-tools'],230),

('carbon','carbon','Carbon',
 'Gera screenshots bonitos de codigo.',
 'Carbon converte snippets de codigo em imagens estilizadas para compartilhar em redes sociais e apresentacoes.',
 'Camera','#1d1d1d','dev-tools','open_source','weblink',
 'https://carbon.now.sh','https://carbon.now.sh','1.0.0','published',
 'free','MIT','Dawn Labs',
 false,true,false,false,false,true,false,
 ARRAY['code','screenshot','dev-tools'],231),

('ray-so','ray-so','Ray.so',
 'Screenshots de codigo com tema Raycast.',
 'Ray.so cria imagens de codigo com temas inspirados em Raycast e suporte a syntax highlight.',
 'Camera','#ff6363','dev-tools','embedded_external','weblink',
 'https://ray.so','https://ray.so','1.0.0','published',
 'free','proprietary','Raycast',
 false,true,false,false,false,true,false,
 ARRAY['code','screenshot','dev-tools'],232),

('crontab-guru','crontab-guru','Crontab Guru',
 'Decodifica expressoes cron em ingles.',
 'Crontab Guru explica expressoes cron em linguagem humana e mostra os proximos disparos.',
 'Clock','#fdaa07','dev-tools','embedded_external','weblink',
 'https://crontab.guru','https://crontab.guru','1.0.0','published',
 'free','proprietary','Cronitor',
 false,true,false,false,false,true,false,
 ARRAY['cron','schedule','dev-tools'],233),

('transform-tools','transform-tools','Transform.tools',
 'Conversor de formatos (JSON, YAML, TS, etc).',
 'Transform.tools converte entre JSON, YAML, TypeScript types, JSON Schema, GraphQL e dezenas de outros formatos.',
 'Repeat','#6366f1','dev-tools','open_source','weblink',
 'https://transform.tools','https://transform.tools','1.0.0','published',
 'free','MIT','ritz078',
 false,true,false,false,false,true,false,
 ARRAY['converter','json','yaml','dev-tools'],234),

('dillinger','dillinger','Dillinger',
 'Editor Markdown online.',
 'Dillinger eh editor Markdown HTML5 com preview ao vivo, sync para Drive/Dropbox/GitHub e exportacao em multiplos formatos.',
 'FileText','#4ec3a1','dev-tools','open_source','weblink',
 'https://dillinger.io','https://dillinger.io','1.0.0','published',
 'free','MIT','joemccann',
 false,true,false,false,false,true,false,
 ARRAY['markdown','editor','dev-tools'],235),

('explainshell','explainshell','ExplainShell',
 'Explica comandos shell linha a linha.',
 'ExplainShell decompoe comandos bash/sh e mostra o significado de cada flag/argumento.',
 'Terminal','#44a8b3','dev-tools','open_source','weblink',
 'https://explainshell.com','https://explainshell.com','1.0.0','published',
 'free','GPL-3.0','idank',
 false,true,false,false,false,true,false,
 ARRAY['shell','bash','dev-tools'],236),

('json-formatter','json-formatter','JSON Formatter',
 'Formatador e validador de JSON.',
 'jsonformatter.org formata, valida e converte JSON para XML/CSV/YAML rapidamente.',
 'FileJson','#ff5722','dev-tools','embedded_external','weblink',
 'https://jsonformatter.org','https://jsonformatter.org','1.0.0','published',
 'free','proprietary','jsonformatter.org',
 false,true,false,false,false,true,false,
 ARRAY['json','formatter','dev-tools'],237),

-- ─── DESIGN extras ──────────────────────────────────────────────────────────

('coolors','coolors','Coolors',
 'Gerador rapido de paletas de cores.',
 'Coolors gera paletas harmonicas com a barra de espaco e suporta exportacao para CSS, SVG, ASE e PDF.',
 'Palette','#ff6b6b','design','embedded_external','weblink',
 'https://coolors.co','https://coolors.co','1.0.0','published',
 'free','proprietary','Coolors',
 false,true,false,false,false,true,false,
 ARRAY['palette','color','design'],249),

('realfavicongenerator','realfavicongenerator','Real Favicon Generator',
 'Gera favicons multi-plataforma.',
 'Real Favicon Generator cria pacotes de favicons compativeis com todos os browsers, iOS, Android e Windows.',
 'Image','#ffd700','design','embedded_external','weblink',
 'https://realfavicongenerator.net','https://realfavicongenerator.net','1.0.0','published',
 'free','proprietary','RealFaviconGenerator',
 false,true,false,false,false,true,false,
 ARRAY['favicon','design'],250),

('pixlr','pixlr','Pixlr',
 'Editor de imagens online.',
 'Pixlr eh suite de edicao de imagens com filtros, layers e templates — alternativa leve ao Photoshop.',
 'Image','#f08080','design','embedded_external','weblink',
 'https://pixlr.com','https://pixlr.com','1.0.0','published',
 'free','proprietary','Pixlr',
 false,true,false,false,false,true,false,
 ARRAY['image','editor','design'],251),

-- ─── DATA & BI ──────────────────────────────────────────────────────────────

('observable','observable','Observable',
 'Notebooks de visualizacao de dados.',
 'Observable HQ permite criar notebooks de data visualization com D3.js, Plot e SQL — alternativa moderna ao Jupyter.',
 'BarChart3','#353a3f','data','embedded_external','weblink',
 'https://observablehq.com','https://observablehq.com','1.0.0','published',
 'free','proprietary','Observable',
 false,true,false,false,false,true,false,
 ARRAY['data-viz','notebook','data'],270),

('kaggle','kaggle','Kaggle',
 'Datasets, notebooks e competicoes ML.',
 'Kaggle hospeda datasets publicos, notebooks colaborativos e competicoes de machine learning.',
 'Database','#20beff','data','embedded_external','weblink',
 'https://www.kaggle.com','https://www.kaggle.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['ml','dataset','notebook','data'],271),

('rawgraphs','rawgraphs','RAWGraphs',
 'Geracao de graficos a partir de planilhas.',
 'RAWGraphs converte CSV/TSV/JSON em graficos vetoriais (SVG) usando D3.js — alternativa open source ao Datawrapper.',
 'PieChart','#ed5b15','data','open_source','weblink',
 'https://app.rawgraphs.io','https://app.rawgraphs.io','1.0.0','published',
 'free','Apache-2.0','DensityDesign',
 false,true,false,false,false,true,false,
 ARRAY['data-viz','svg','open-source','data'],272),

('google-trends','google-trends','Google Trends',
 'Tendencias de busca em tempo real.',
 'Google Trends explora popularidade de termos de busca por regiao e periodo.',
 'TrendingUp','#4285f4','data','embedded_external','weblink',
 'https://trends.google.com','https://trends.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['trends','search','data'],273),

('duckdb-shell','duckdb-shell','DuckDB Shell',
 'Banco de dados analitico no browser.',
 'DuckDB Shell roda DuckDB-Wasm direto no navegador para queries analiticas em CSV/Parquet/JSON.',
 'Database','#fff100','data','open_source','weblink',
 'https://shell.duckdb.org','https://shell.duckdb.org','1.0.0','published',
 'free','MIT','DuckDB Foundation',
 false,true,false,false,false,true,false,
 ARRAY['duckdb','sql','wasm','data'],274),

-- ─── JOGOS extras ───────────────────────────────────────────────────────────

('game-tetris','game-tetris','Tetris',
 'Tetris classico online.',
 'Tetris.com eh implementacao oficial do classico jogo de blocos.',
 'Grid3x3','#009639','games','embedded_external','weblink',
 'https://www.tetris.com','https://www.tetris.com','1.0.0','published',
 'free','proprietary','Tetris',
 false,true,false,false,false,true,false,
 ARRAY['tetris','puzzle','games'],315),

('game-typeracer','game-typeracer','TypeRacer',
 'Corrida de digitacao multiplayer.',
 'TypeRacer mede WPM em corridas contra outros jogadores em tempo real.',
 'Keyboard','#fcb40e','games','embedded_external','weblink',
 'https://play.typeracer.com','https://play.typeracer.com','1.0.0','published',
 'free','proprietary','TypeRacer',
 false,true,false,false,false,true,false,
 ARRAY['typing','multiplayer','games'],316),

('game-codecombat','game-codecombat','CodeCombat',
 'Aprenda programacao jogando.',
 'CodeCombat ensina Python, JavaScript e algoritmos atraves de mini-jogos.',
 'Code','#c46f29','games','open_source','weblink',
 'https://codecombat.com','https://codecombat.com','1.0.0','published',
 'free','MIT','CodeCombat',
 false,true,false,false,false,true,false,
 ARRAY['coding','education','games'],317),

('game-cookie-clicker','game-cookie-clicker','Cookie Clicker',
 'Idle game incremental classico.',
 'Cookie Clicker eh idle game viciante: clique no cookie, suba upgrades, automatize e nunca pare.',
 'Cookie','#d2691e','games','embedded_external','weblink',
 'https://orteil.dashnet.org/cookieclicker/','https://orteil.dashnet.org/cookieclicker/','1.0.0','published',
 'free','proprietary','Orteil',
 false,true,false,false,false,true,false,
 ARRAY['idle','incremental','games'],318),

('game-typingclub','game-typingclub','TypingClub',
 'Curso de digitacao gamificado.',
 'TypingClub ensina digitacao com licoes progressivas e gamification.',
 'Keyboard','#2196f3','games','embedded_external','weblink',
 'https://www.typingclub.com','https://www.typingclub.com','1.0.0','published',
 'free','proprietary','EdClub',
 false,true,false,false,false,true,false,
 ARRAY['typing','education','games'],319),

('game-mahjong','game-mahjong','Mahjong Solitaire',
 'Mahjong classico no navegador.',
 'Mahjong Solitaire em HTML5 com varias layouts e dificuldades.',
 'Grid3x3','#8b4513','games','embedded_external','weblink',
 'https://www.solitr.com/mahjong','https://www.solitr.com/mahjong','1.0.0','published',
 'free','proprietary','Solitr',
 false,true,false,false,false,true,false,
 ARRAY['mahjong','puzzle','games'],320),

-- ─── FINANCAS & MERCADO ─────────────────────────────────────────────────────

('tradingview-chart','tradingview-chart','TradingView Chart',
 'Graficos profissionais de acoes/crypto.',
 'Widget oficial do TradingView com grafico avancado, indicadores tecnicos e drawing tools embedaveis.',
 'CandlestickChart','#2962ff','data','embedded_external','iframe',
 'https://www.tradingview.com/widgetembed/?frameElementId=tv_chart&symbol=AAPL&interval=D&hidesidetoolbar=0&symboledit=1&saveimage=0&toolbarbg=f1f3f6&studies=[]&theme=Dark&style=1&timezone=exchange&studies_overrides={}&overrides={}&enabled_features=[]&disabled_features=[]&locale=br',
 'https://www.tradingview.com','1.0.0','published',
 'free','proprietary','TradingView',
 false,true,false,false,false,true,false,
 ARRAY['stocks','crypto','charts','finance','data'],330),

('tradingview-screener','tradingview-screener','TradingView Screener',
 'Scanner de acoes com filtros.',
 'Filtra acoes por dezenas de criterios fundamentalistas e tecnicos via widget oficial TradingView.',
 'Filter','#2962ff','data','embedded_external','iframe',
 'https://www.tradingview.com/widget/screener/','https://www.tradingview.com/screener','1.0.0','published',
 'free','proprietary','TradingView',
 false,true,false,false,false,true,false,
 ARRAY['stocks','screener','finance','data'],331),

('tradingview-heatmap','tradingview-heatmap','TradingView Heatmap',
 'Mapa de calor do mercado crypto.',
 'Heatmap em tempo real do mercado crypto com cap de mercado e variacao 24h.',
 'LayoutGrid','#2962ff','data','embedded_external','iframe',
 'https://www.tradingview.com/widget/crypto-mkt-screener/','https://www.tradingview.com/markets/cryptocurrencies/','1.0.0','published',
 'free','proprietary','TradingView',
 false,true,false,false,false,true,false,
 ARRAY['crypto','heatmap','data'],332),

('tradingview-ticker','tradingview-ticker','TradingView Ticker',
 'Ticker de precos ao vivo.',
 'Ticker tape com cotacoes em tempo real de simbolos selecionados.',
 'Activity','#2962ff','data','embedded_external','iframe',
 'https://www.tradingview.com/widget/ticker-tape/','https://www.tradingview.com','1.0.0','published',
 'free','proprietary','TradingView',
 false,true,false,false,false,true,false,
 ARRAY['ticker','stocks','data'],333),

('coingecko','coingecko','CoinGecko',
 'Precos de criptomoedas em tempo real.',
 'CoinGecko rastreia precos, volume e market cap de milhares de criptomoedas.',
 'Coins','#8dc647','data','embedded_external','iframe',
 'https://www.coingecko.com','https://www.coingecko.com','1.0.0','published',
 'free','proprietary','CoinGecko',
 false,true,false,false,false,true,false,
 ARRAY['crypto','prices','data'],334),

('coinmarketcap','coinmarketcap','CoinMarketCap',
 'Ranking e capitalizacao crypto.',
 'CoinMarketCap eh referencia em ranking de criptomoedas por market cap, com widgets oficiais.',
 'TrendingUp','#3861fb','data','embedded_external','weblink',
 'https://coinmarketcap.com/widget/','https://coinmarketcap.com','1.0.0','published',
 'free','proprietary','CoinMarketCap',
 false,true,false,false,false,true,false,
 ARRAY['crypto','ranking','data'],335),

('xe-currency','xe-currency','XE Currency',
 'Conversor de moedas ao vivo.',
 'XE.com oferece conversao de moedas e cotacoes em tempo real.',
 'DollarSign','#015aaa','data','embedded_external','iframe',
 'https://www.xe.com/currencyconverter/','https://www.xe.com','1.0.0','published',
 'free','proprietary','XE.com',
 false,true,false,false,false,true,false,
 ARRAY['currency','converter','data'],336),

('yahoo-finance','yahoo-finance','Yahoo Finance',
 'Noticias e cotacoes financeiras.',
 'Yahoo Finance reune noticias, cotacoes, charts e analises de mercado.',
 'Newspaper','#7e1fff','data','embedded_external','weblink',
 'https://finance.yahoo.com','https://finance.yahoo.com','1.0.0','published',
 'free','proprietary','Yahoo',
 false,true,false,false,false,true,false,
 ARRAY['stocks','news','data'],337),

('investing-com','investing-com','Investing.com',
 'Calendario economico e charts.',
 'Investing.com agrega calendario economico, indices, criptos, commodities e widgets gratuitos.',
 'BarChart3','#003b6f','data','embedded_external','weblink',
 'https://www.investing.com/webmaster-tools/','https://www.investing.com','1.0.0','published',
 'free','proprietary','Investing.com',
 false,true,false,false,false,true,false,
 ARRAY['stocks','economic-calendar','data'],338),

('google-finance','google-finance','Google Finance',
 'Cotacoes de acoes e indices.',
 'Google Finance exibe cotacoes, charts e noticias de empresas listadas globalmente.',
 'LineChart','#4285f4','data','embedded_external','iframe',
 'https://www.google.com/finance/','https://www.google.com/finance/','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['stocks','finance','data'],339),

-- ─── EDUCACAO & REFERENCIA ──────────────────────────────────────────────────

('wikipedia','wikipedia','Wikipedia',
 'Enciclopedia colaborativa universal.',
 'Wikipedia eh enciclopedia livre em centenas de idiomas, mantida pela Wikimedia Foundation.',
 'BookOpen','#000000','productivity','open_source','iframe',
 'https://en.wikipedia.org','https://en.wikipedia.org','1.0.0','published',
 'free','CC-BY-SA-4.0','Wikimedia',
 false,true,false,false,false,true,false,
 ARRAY['encyclopedia','reference','open-source'],340),

('wolfram-alpha','wolfram-alpha','Wolfram Alpha',
 'Motor de conhecimento computacional.',
 'Wolfram Alpha resolve calculos matematicos, ciencia, dados estatisticos e questoes factuais.',
 'Sigma','#dc241f','dev-tools','embedded_external','iframe',
 'https://www.wolframalpha.com','https://www.wolframalpha.com','1.0.0','published',
 'free','proprietary','Wolfram',
 false,true,false,false,false,true,false,
 ARRAY['math','computation','reference'],341),

('google-translate','google-translate','Google Translate',
 'Tradutor universal Google.',
 'Google Translate suporta 100+ idiomas com traducao texto, voz, imagem e documentos.',
 'Languages','#4285f4','utilities','embedded_external','iframe',
 'https://translate.google.com','https://translate.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['translation','google','utilities'],342),

('deepl','deepl','DeepL',
 'Tradutor IA de alta qualidade.',
 'DeepL eh tradutor neural com qualidade superior em pares europeu/asiatico, ideal para textos profissionais.',
 'Languages','#0f2b46','utilities','embedded_external','weblink',
 'https://www.deepl.com/translator','https://www.deepl.com','1.0.0','published',
 'free','proprietary','DeepL',
 false,true,false,false,false,true,false,
 ARRAY['translation','ai','utilities'],343),

('khan-academy','khan-academy','Khan Academy',
 'Cursos online gratuitos.',
 'Khan Academy oferece milhares de licoes de matematica, ciencias e humanidades em portugues e ingles.',
 'GraduationCap','#14bf96','productivity','embedded_external','weblink',
 'https://www.khanacademy.org','https://www.khanacademy.org','1.0.0','published',
 'free','proprietary','Khan Academy',
 false,true,false,false,false,true,false,
 ARRAY['education','courses','productivity'],344),

('desmos','desmos','Desmos Calculator',
 'Calculadora grafica avancada.',
 'Desmos eh calculadora grafica interativa para funcoes, geometria e estatistica — embed oficial.',
 'Calculator','#127c4a','productivity','embedded_external','iframe',
 'https://www.desmos.com/calculator','https://www.desmos.com/calculator','1.0.0','published',
 'free','proprietary','Desmos',
 false,true,false,false,false,true,false,
 ARRAY['math','calculator','education'],345),

('geogebra','geogebra','GeoGebra',
 'Matematica interativa (geometria/algebra).',
 'GeoGebra integra geometria, algebra, calculo e estatistica em ferramenta unica para educacao.',
 'Compass','#9999ff','productivity','open_source','iframe',
 'https://www.geogebra.org/calculator','https://www.geogebra.org','1.0.0','published',
 'free','GPL-3.0','GeoGebra',
 false,true,false,false,false,true,false,
 ARRAY['math','geometry','education','open-source'],346),

('google-scholar','google-scholar','Google Scholar',
 'Busca academica.',
 'Google Scholar indexa artigos cientificos, teses, livros e citacoes academicas.',
 'BookMarked','#4285f4','productivity','embedded_external','weblink',
 'https://scholar.google.com','https://scholar.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['research','academic','productivity'],347),

-- ─── COMUNICACAO & COLABORACAO ──────────────────────────────────────────────

('calendly','calendly','Calendly',
 'Agendamento de reunioes.',
 'Calendly automatiza agendamento via links compartilhaveis com integracao a calendarios e Zoom/Teams.',
 'Calendar','#006bff','productivity','embedded_external','iframe',
 'https://calendly.com','https://calendly.com','1.0.0','published',
 'free','proprietary','Calendly',
 false,true,false,false,false,true,false,
 ARRAY['scheduling','meetings','productivity'],350),

('typeform','typeform','Typeform',
 'Formularios interativos com UX premium.',
 'Typeform cria formularios conversacionais com transicoes suaves — embed oficial via iframe.',
 'FormInput','#262627','productivity','embedded_external','iframe',
 'https://www.typeform.com','https://www.typeform.com','1.0.0','published',
 'free','proprietary','Typeform',
 false,true,false,false,false,true,false,
 ARRAY['forms','surveys','productivity'],351),

('tally','tally','Tally',
 'Formularios gratuitos sem limites.',
 'Tally eh alternativa Typeform/Google Forms — formularios ilimitados gratis com embed nativo.',
 'FileSpreadsheet','#0f9960','productivity','embedded_external','iframe',
 'https://tally.so','https://tally.so','1.0.0','published',
 'free','proprietary','Tally',
 false,true,false,false,false,true,false,
 ARRAY['forms','surveys','productivity'],352),

('jitsi-meet','jitsi-meet','Jitsi Meet',
 'Videoconferencia open source.',
 'Jitsi Meet eh plataforma de videoconferencia open source com salas instantaneas via iframe oficial.',
 'Video','#1071e5','productivity','open_source','iframe',
 'https://meet.jit.si','https://meet.jit.si','1.0.0','published',
 'free','Apache-2.0','Jitsi',
 false,true,false,false,false,true,false,
 ARRAY['video','meetings','open-source'],353),

('whereby','whereby','Whereby',
 'Videoconferencia embeddable.',
 'Whereby permite criar salas de video instantaneas e embedalas em sites/apps via iframe.',
 'Video','#fdb316','productivity','embedded_external','iframe',
 'https://whereby.com','https://whereby.com','1.0.0','published',
 'free','proprietary','Whereby',
 false,true,false,false,false,true,false,
 ARRAY['video','meetings','productivity'],354),

('loom','loom','Loom',
 'Gravacao de tela com video facial.',
 'Loom grava tela + camera para enviar mensagens de video assincronas, com embed oficial dos videos.',
 'VideoIcon','#625df5','productivity','embedded_external','iframe',
 'https://www.loom.com','https://www.loom.com','1.0.0','published',
 'free','proprietary','Loom',
 false,true,false,false,false,true,false,
 ARRAY['video','screen-recording','productivity'],355),

-- ─── MIDIA & CONTEUDO ───────────────────────────────────────────────────────

('youtube','youtube','YouTube',
 'Plataforma de videos do Google.',
 'YouTube hospeda bilhoes de videos com player embeddable via iframe oficial.',
 'Youtube','#ff0000','utilities','embedded_external','iframe',
 'https://www.youtube.com','https://www.youtube.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['video','media','utilities'],360),

('spotify','spotify','Spotify',
 'Streaming de musica e podcasts.',
 'Spotify oferece embed player oficial para playlists, albums e podcasts.',
 'Music','#1db954','utilities','embedded_external','iframe',
 'https://open.spotify.com','https://open.spotify.com','1.0.0','published',
 'free','proprietary','Spotify',
 false,true,false,false,false,true,false,
 ARRAY['music','podcast','media'],361),

('vimeo','vimeo','Vimeo',
 'Hospedagem de videos profissionais.',
 'Vimeo hospeda videos em alta qualidade com player embeddable.',
 'Video','#1ab7ea','utilities','embedded_external','iframe',
 'https://vimeo.com','https://vimeo.com','1.0.0','published',
 'free','proprietary','Vimeo',
 false,true,false,false,false,true,false,
 ARRAY['video','media','utilities'],362),

('soundcloud','soundcloud','SoundCloud',
 'Streaming de audio e podcasts.',
 'SoundCloud distribui audios e podcasts independentes com widget oficial.',
 'Music','#ff5500','utilities','embedded_external','iframe',
 'https://soundcloud.com','https://soundcloud.com','1.0.0','published',
 'free','proprietary','SoundCloud',
 false,true,false,false,false,true,false,
 ARRAY['audio','podcast','media'],363),

('twitch','twitch','Twitch',
 'Streaming ao vivo (gaming/tech).',
 'Twitch eh plataforma lider em streaming ao vivo com player embeddable por canal.',
 'Tv','#9146ff','utilities','embedded_external','iframe',
 'https://www.twitch.tv','https://www.twitch.tv','1.0.0','published',
 'free','proprietary','Twitch',
 false,true,false,false,false,true,false,
 ARRAY['video','live','streaming'],364),

('mixcloud','mixcloud','Mixcloud',
 'DJ sets e podcasts longos.',
 'Mixcloud hospeda DJ sets, radio shows e podcasts com widget iframe oficial.',
 'Disc3','#314359','utilities','embedded_external','iframe',
 'https://www.mixcloud.com','https://www.mixcloud.com','1.0.0','published',
 'free','proprietary','Mixcloud',
 false,true,false,false,false,true,false,
 ARRAY['audio','dj','media'],365),

('giphy','giphy','GIPHY',
 'Biblioteca de GIFs animados.',
 'GIPHY hospeda milhoes de GIFs com embed oficial — util para reacoes e mensagens visuais.',
 'Image','#04fa6e','utilities','embedded_external','iframe',
 'https://giphy.com','https://giphy.com','1.0.0','published',
 'free','proprietary','GIPHY',
 false,true,false,false,false,true,false,
 ARRAY['gif','reactions','media'],366),

('unsplash','unsplash','Unsplash',
 'Banco de imagens gratuitas.',
 'Unsplash oferece fotos profissionais gratuitas para uso comercial e pessoal.',
 'Image','#000000','design','embedded_external','iframe',
 'https://unsplash.com','https://unsplash.com','1.0.0','published',
 'free','proprietary','Unsplash',
 false,true,false,false,false,true,false,
 ARRAY['photos','stock','design'],367),

('pexels','pexels','Pexels',
 'Fotos e videos gratuitos.',
 'Pexels oferece fotos e videos em alta resolucao gratuitos para qualquer uso.',
 'Image','#05a081','design','embedded_external','iframe',
 'https://www.pexels.com','https://www.pexels.com','1.0.0','published',
 'free','proprietary','Pexels',
 false,true,false,false,false,true,false,
 ARRAY['photos','videos','stock','design'],368),

('google-arts','google-arts','Google Arts & Culture',
 'Museus e arte virtual.',
 'Arts & Culture do Google leva voce a museus, exposicoes e patrimonio cultural mundial.',
 'Palette','#ea4335','utilities','embedded_external','iframe',
 'https://artsandculture.google.com','https://artsandculture.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['art','culture','museum'],369),

-- ─── DESIGN & PROTOTIPAGEM (extras embeddable) ──────────────────────────────

('figma-embed','figma-embed','Figma Prototypes',
 'Preview de prototipos Figma.',
 'Embed oficial Figma para mostrar prototipos publicos sem precisar abrir o app desktop.',
 'Figma','#f24e1e','design','embedded_external','iframe',
 'https://www.figma.com/embed','https://www.figma.com','1.0.0','published',
 'free','proprietary','Figma Inc.',
 false,true,false,false,false,true,false,
 ARRAY['prototype','design','figma'],370),

('canva-published','canva-published','Canva Published',
 'Visualizacao publicada de designs Canva.',
 'Designs publicados do Canva podem ser visualizados em iframe via URL /view.',
 'Palette','#00c4cc','design','embedded_external','iframe',
 'https://www.canva.com/design/','https://www.canva.com','1.0.0','published',
 'free','proprietary','Canva',
 false,true,false,false,false,true,false,
 ARRAY['design','canva','published'],371),

('miro','miro','Miro',
 'Whiteboard colaborativo (live embed).',
 'Miro eh whiteboard online com live embed para boards publicos — collab visual em tempo real.',
 'PenTool','#ffd02f','productivity','embedded_external','iframe',
 'https://miro.com','https://miro.com','1.0.0','published',
 'free','proprietary','Miro',
 false,true,false,false,false,true,false,
 ARRAY['whiteboard','collab','productivity'],372),

('codepen','codepen','CodePen',
 'Demos HTML/CSS/JS embeddaveis.',
 'CodePen eh playground de front-end com embed oficial de pens publicos.',
 'Code','#000000','dev-tools','embedded_external','iframe',
 'https://codepen.io','https://codepen.io','1.0.0','published',
 'free','proprietary','CodePen',
 false,true,false,false,false,true,false,
 ARRAY['html','css','js','playground','dev-tools'],373),

('observable-embed','observable-embed','Observable Embed',
 'Notebooks de dados embeddaveis.',
 'Embed oficial de notebooks Observable HQ (alternativa ao Jupyter) para data viz.',
 'BarChart3','#353a3f','data','embedded_external','iframe',
 'https://observablehq.com/embed','https://observablehq.com','1.0.0','published',
 'free','proprietary','Observable',
 false,true,false,false,false,true,false,
 ARRAY['data-viz','notebook','data'],374),

('slideshare','slideshare','SlideShare',
 'Apresentacoes publicas embeddaveis.',
 'SlideShare hospeda apresentacoes corporativas e educacionais com embed oficial.',
 'Presentation','#1a73e8','productivity','embedded_external','iframe',
 'https://www.slideshare.net','https://www.slideshare.net','1.0.0','published',
 'free','proprietary','Scribd',
 false,true,false,false,false,true,false,
 ARRAY['slides','presentation','productivity'],375),

-- ─── MAPAS & LOCALIZACAO ────────────────────────────────────────────────────

('google-maps','google-maps','Google Maps',
 'Mapas interativos com Embed API.',
 'Google Maps Embed API permite incluir mapas dinamicos com Street View, direcoes e places.',
 'MapPin','#34a853','utilities','embedded_external','iframe',
 'https://www.google.com/maps','https://www.google.com/maps','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['maps','navigation','utilities'],380),

('openstreetmap','openstreetmap','OpenStreetMap',
 'Mapas open source colaborativos.',
 'OpenStreetMap eh alternativa colaborativa ao Google Maps, com licenca aberta ODbL.',
 'Map','#7ebc6f','utilities','open_source','iframe',
 'https://www.openstreetmap.org','https://www.openstreetmap.org','1.0.0','published',
 'free','ODbL-1.0','OpenStreetMap',
 false,true,false,false,false,true,false,
 ARRAY['maps','open-source','utilities'],381),

('google-earth','google-earth','Google Earth',
 'Globo 3D interativo.',
 'Google Earth navega Terra em 3D com imagens de satelite e Street View imersivo.',
 'Globe','#4285f4','utilities','embedded_external','iframe',
 'https://earth.google.com/web/','https://earth.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['maps','3d','earth'],382),

('windy','windy','Windy',
 'Mapa meteorologico em tempo real.',
 'Windy.com mostra mapas de vento, chuva, temperatura e tempestades com embed oficial.',
 'Wind','#3eaf3e','utilities','embedded_external','iframe',
 'https://www.windy.com','https://www.windy.com','1.0.0','published',
 'free','proprietary','Windy',
 false,true,false,false,false,true,false,
 ARRAY['weather','maps','utilities'],383),

-- ─── PRODUTIVIDADE GOOGLE ───────────────────────────────────────────────────

('google-docs','google-docs','Google Docs',
 'Editor de texto colaborativo.',
 'Google Docs publica documentos em iframe via /pub.',
 'FileText','#4285f4','productivity','embedded_external','iframe',
 'https://docs.google.com/document/','https://docs.google.com/document/','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['docs','google','productivity'],390),

('google-sheets','google-sheets','Google Sheets',
 'Planilhas colaborativas Google.',
 'Sheets publicadas via /pubhtml podem ser embedadas em iframe.',
 'Sheet','#0f9d58','productivity','embedded_external','iframe',
 'https://docs.google.com/spreadsheets/','https://docs.google.com/spreadsheets/','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['sheets','google','productivity'],391),

('google-slides','google-slides','Google Slides',
 'Apresentacoes Google.',
 'Slides Google embeddaveis via /embed — ideal para apresentacoes em workspace.',
 'Presentation','#fbbc04','productivity','embedded_external','iframe',
 'https://docs.google.com/presentation/','https://docs.google.com/presentation/','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['slides','google','productivity'],392),

('google-forms','google-forms','Google Forms',
 'Formularios Google embeddaveis.',
 'Google Forms suporta embed oficial via ?embedded=true.',
 'FormInput','#673ab7','productivity','embedded_external','iframe',
 'https://docs.google.com/forms/','https://docs.google.com/forms/','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['forms','google','productivity'],393),

('google-calendar','google-calendar','Google Calendar',
 'Calendario Google embeddavel.',
 'Calendarios publicos podem ser embedados via /embed?src=...',
 'Calendar','#4285f4','productivity','embedded_external','iframe',
 'https://calendar.google.com','https://calendar.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['calendar','google','productivity'],394),

('looker-studio','looker-studio','Looker Studio',
 'Dashboards de dados (Data Studio).',
 'Looker Studio (ex-Data Studio) cria dashboards conectados a multiplos datasources com embed.',
 'BarChart','#34a853','data','embedded_external','iframe',
 'https://lookerstudio.google.com','https://lookerstudio.google.com','1.0.0','published',
 'free','proprietary','Google',
 false,true,false,false,false,true,false,
 ARRAY['dashboard','analytics','data'],395),

-- ─── NOTICIAS & INFORMACAO ──────────────────────────────────────────────────

('hacker-news','hacker-news','Hacker News',
 'Comunidade tech / Y Combinator.',
 'Hacker News eh agregador de noticias tech do Y Combinator, com discussoes de alto sinal.',
 'Newspaper','#ff6600','utilities','embedded_external','iframe',
 'https://news.ycombinator.com','https://news.ycombinator.com','1.0.0','published',
 'free','proprietary','Y Combinator',
 false,true,false,false,false,true,false,
 ARRAY['news','tech','community'],400),

('reddit','reddit','Reddit',
 'Foruns de discussao tematicos.',
 'Reddit organiza comunidades (subreddits) por tema com posts, comentarios e votos.',
 'MessageSquare','#ff4500','utilities','embedded_external','weblink',
 'https://www.reddit.com','https://www.reddit.com','1.0.0','published',
 'free','proprietary','Reddit',
 false,true,false,false,false,true,false,
 ARRAY['social','community','news'],401),

('product-hunt','product-hunt','Product Hunt',
 'Descoberta de produtos novos.',
 'Product Hunt destaca lancamentos de produtos digitais com upvotes da comunidade.',
 'Rocket','#da552f','utilities','embedded_external','weblink',
 'https://www.producthunt.com','https://www.producthunt.com','1.0.0','published',
 'free','proprietary','Product Hunt',
 false,true,false,false,false,true,false,
 ARRAY['products','startups','discovery'],402),

('techcrunch','techcrunch','TechCrunch',
 'Noticias de startups e tech.',
 'TechCrunch cobre rounds de investimento, lancamentos e tendencias do ecossistema startup.',
 'Newspaper','#0a9928','utilities','embedded_external','weblink',
 'https://techcrunch.com','https://techcrunch.com','1.0.0','published',
 'free','proprietary','Yahoo',
 false,true,false,false,false,true,false,
 ARRAY['news','startups','tech'],403),

('weather-underground','weather-underground','Weather Underground',
 'Previsao do tempo detalhada.',
 'Weather Underground oferece widgets meteorologicos detalhados com radar e dados historicos.',
 'CloudRain','#ff6b00','utilities','embedded_external','iframe',
 'https://www.wunderground.com','https://www.wunderground.com','1.0.0','published',
 'free','proprietary','IBM',
 false,true,false,false,false,true,false,
 ARRAY['weather','widget','utilities'],404),

('accuweather','accuweather','AccuWeather',
 'Previsao meteorologica global.',
 'AccuWeather oferece widgets oficiais de previsao do tempo para qualquer cidade.',
 'CloudSun','#ff6633','utilities','embedded_external','iframe',
 'https://www.accuweather.com','https://www.accuweather.com','1.0.0','published',
 'free','proprietary','AccuWeather',
 false,true,false,false,false,true,false,
 ARRAY['weather','widget','utilities'],405),

('worldtimebuddy','worldtimebuddy','World Time Buddy',
 'Comparador de fusos horarios.',
 'World Time Buddy compara horarios entre cidades — util para reunioes globais.',
 'Clock','#367fa9','utilities','embedded_external','iframe',
 'https://www.worldtimebuddy.com','https://www.worldtimebuddy.com','1.0.0','published',
 'free','proprietary','WTB',
 false,true,false,false,false,true,false,
 ARRAY['timezone','meetings','utilities'],406)

ON CONFLICT (id) DO NOTHING;

COMMENT ON CONSTRAINT app_registry_category_check ON kernel.app_registry IS
  'Sprint 25 MX137: extendido com dev-tools, design e data para suportar catalogo open source.';
